### ISSUE TITLE
Dokumentation für Zwischenabgabe erstellen

### ISSUE THREAD

**Issue by Dachgruber** [Dachgruber/Castaway#1]
Dokumentationsfile muss erstellt und erste Texte über unsere Vorbereitung geschrieben werden.

**Comment by charlottaEinhorn** [comment]
[Dokumentation.docx](https://github.com/Dachgruber/Castaway/files/3550380/Dokumentation.docx)

**Comment by charlottaEinhorn** [comment]
[Dokumentation.docx](https://github.com/Dachgruber/Castaway/files/3550481/Dokumentation.docx)

**Comment by charlottaEinhorn** [comment]
[Dokumentation.docx](https://github.com/Dachgruber/Castaway/files/3574151/Dokumentation.docx)

**Comment by charlottaEinhorn** [comment]
Es fehlen nur noch 3 Karten und die tabellarische Darstellung der Projekte

**Comment by Dachgruber** [comment]
Aktualisierung untger Umständen von Nöten, dann bitte reopen oder neu erstellen
