### ISSUE TITLE
System auslagern

### ISSUE THREAD

**Issue by Messallaa** [Dachgruber/Castaway#13]
Alle systemabhängigen Funktionen (System.out.print) auslagern in eine extra Klasse, um im Falle eines System wechsel nur eine Klasse ändern zu müssen.

**Comment by Tom-crtl** [comment]
Hi.

**Comment by Dachgruber** [comment]
Story-Elemente sind nun in Klasse "Story" wiederzufinden. Kleine Einzeiler bleiben noch im Projekt verstreut

**Comment by Dachgruber** [comment]
Nach Implementierung des GUI redundant geworden. Wird nun geschlossen
