### ISSUE TITLE
Enum - Befehl variablen

### ISSUE THREAD

**Issue by Messallaa** [Dachgruber/Castaway#15]
Befehlslager. Wichtig damit zu starten

**Comment by Messallaa** [comment]
public enum commands
{ GO, WALK, ...}                             Alles Uppercase

message=""
commands move= commands.GO;
switch(move)
{
case GO:
case MOVE:
case ...
message="Move Befehl";
Break;

**Comment by Messallaa** [comment]
https://www.heise.de/tipps-tricks/Java-enums-so-geht-s-4055338.html

**Comment by Dachgruber** [comment]
Enums sind erstmal beerdigt, wird wieder aufgegriffen wenn im Dezember noch Zeit bleibt
